"""The CatalogStore Protocol recognizes a complete backend and rejects a partial one."""

from mesa_ducklake.catalog_base import CatalogStore


class _Complete:
    def register_project(self, *a, **k): ...
    def get_project(self, *a, **k): ...
    def find_project_by_path(self, *a, **k): ...
    def create_snapshot(self, *a, **k): ...
    def update_snapshot_parquet_file(self, *a, **k): ...
    def delete_snapshot(self, *a, **k): ...
    def latest_snapshot_id(self, *a, **k): ...
    def list_snapshots(self, *a, **k): ...
    def get_snapshot(self, *a, **k): ...
    def snapshot_ts(self, *a, **k): ...
    def insert_pending_push(self, *a, **k): ...
    def delete_pending_push(self, *a, **k): ...
    def bump_pending_push_attempt(self, *a, **k): ...
    def list_pending_pushes(self, *a, **k): ...
    def get_pending_push(self, *a, **k): ...
    def close(self): ...


class _Partial:
    def register_project(self, *a, **k): ...


def test_complete_backend_satisfies_protocol():
    assert isinstance(_Complete(), CatalogStore)


def test_partial_backend_does_not_satisfy_protocol():
    assert not isinstance(_Partial(), CatalogStore)
